data_source retail:
  type: bigquery
  connection:
    account_info_json_path: # path_to_your_gcs_connection_file
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: # your_project_id
    dataset: retail
soda_cloud:
  host: cloud.soda.io
  api_key_id: your_soda_api_key_id
  api_key_secret: # your_soda_api_key_secret